services:
  - type: web
    name: frat-treasurer-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: frat-treasurer-db
          property: connectionString

databases:
  - name: frat-treasurer-db
    databaseName: fraternity
    user: treasurer
